# Generated by Django 4.2.5 on 2024-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('unitat_de_mesura', models.CharField(choices=[('u', 'Unitats'), ('kg', 'Quilograms'), ('T', 'Tonelades')], default='u', max_length=2)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preu_venta', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Article del proveïdor',
                'verbose_name_plural': '02 - Articles del proveïdor',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Capacitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('tipus', models.CharField(choices=[('co', 'Corral'), ('al', 'Aliment'), ('re', 'Rebuig')], max_length=2)),
                ('capacitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Capacitat',
                'verbose_name_plural': '06 - Capacitats',
                'ordering': ['tipus', 'capacitat'],
            },
        ),
        migrations.CreateModel(
            name='ComandesProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('data_comanda', models.DateField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('observacions', models.TextField(blank=True, null=True, verbose_name='Observacions')),
            ],
            options={
                'verbose_name': 'Comanda del proveïdor',
                'verbose_name_plural': '03 - Comandes del proveïdor',
                'ordering': ['-data_comanda'],
            },
        ),
        migrations.CreateModel(
            name='DetallComandaProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('processada', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.articlesproveidor')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.comandesproveidor')),
            ],
            options={
                'verbose_name': 'Detall de la comanda del proveïdor',
                'verbose_name_plural': '04 - Detalls de la comanda (PROV.)',
                'ordering': ['comanda'],
            },
        ),
        migrations.CreateModel(
            name='Proveidors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('persona_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globg.personalegal')),
            ],
            options={
                'verbose_name': 'Proveïdor',
                'verbose_name_plural': '01 - Proveïdors',
                'ordering': ['persona_legal__nom'],
            },
        ),
        migrations.CreateModel(
            name='EntradesDeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assignats_a_corral', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.articlesproveidor')),
                ('detall_comanda_proveidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.detallcomandaproveidor')),
            ],
            options={
                'verbose_name': 'Entrada de material',
                'verbose_name_plural': '05 - Entrades de material',
                'ordering': ['detall_comanda_proveidor'],
            },
        ),
        migrations.AddField(
            model_name='comandesproveidor',
            name='proveidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.proveidors'),
        ),
        migrations.CreateModel(
            name='CapacitatEstoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.articlesproveidor')),
                ('capacitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.capacitat')),
                ('tipus_producte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globg.tipusproducte')),
            ],
            options={
                'verbose_name': 'Capacitat estoc',
                'verbose_name_plural': '07 - Capacitats estoc',
                'ordering': ['capacitat__tipus', 'capacitat__capacitat'],
            },
        ),
        migrations.AddField(
            model_name='articlesproveidor',
            name='proveidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.proveidors'),
        ),
        migrations.AddField(
            model_name='articlesproveidor',
            name='tipus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globg.tipusproducte'),
        ),
    ]
