# Generated by Django 4.2.5 on 2024-04-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globg', '0002_categoriacorral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveidors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('persona_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globg.personalegal')),
            ],
            options={
                'verbose_name': 'Proveïdor',
                'verbose_name_plural': 'Proveïdors',
                'ordering': ['persona_legal__nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticlesProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('unitat_de_mesura', models.CharField(choices=[('u', 'Unitats'), ('kg', 'Quilograms'), ('T', 'Tonelades')], default='u', max_length=2)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria_corral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globg.categoriacorral')),
                ('proveidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.proveidors')),
            ],
            options={
                'verbose_name': 'Article del proveïdor',
                'verbose_name_plural': 'Articles del proveïdor',
                'ordering': ['nom'],
            },
        ),
    ]
