# Generated by Django 4.2.5 on 2024-04-18 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('explotacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandesProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('data_comanda', models.DateField(default=django.utils.timezone.now)),
                ('data_entrega', models.DateField(default=django.utils.timezone.now)),
                ('observacions', models.TextField(blank=True, null=True, verbose_name='Observacions')),
                ('proveidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.proveidors')),
            ],
            options={
                'verbose_name': 'Comanda del proveïdor',
                'verbose_name_plural': 'Comandes del proveïdor',
                'ordering': ['data_comanda'],
            },
        ),
        migrations.CreateModel(
            name='DetallComandaProveidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.articlesproveidor')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.comandesproveidor')),
            ],
            options={
                'verbose_name': 'Detall de la comanda del proveïdor',
                'verbose_name_plural': 'Detalls de la comanda del proveïdor',
                'ordering': ['comanda'],
            },
        ),
        migrations.CreateModel(
            name='EntradesDeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('assignats_a_corral', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detall_comanda_proveidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.detallcomandaproveidor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
