# Generated by Django 4.2.5 on 2024-04-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explotacio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesproveidor',
            old_name='preu_venta',
            new_name='preu_venda',
        ),
    ]
