# Generated by Django 4.2.5 on 2024-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explotacio', '0003_alter_entradesdematerial_assignats_a_corral'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallcomandaproveidor',
            name='processada',
            field=models.BooleanField(default=False),
        ),
    ]
