# Generated by Django 4.2.5 on 2024-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explotacio', '0004_detallcomandaproveidor_processada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('tipus', models.CharField(choices=[('co', 'Corral'), ('al', 'Aliment'), ('re', 'Rebuig')], max_length=2)),
                ('capacitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
            ],
            options={
                'verbose_name': 'Capacitat',
                'verbose_name_plural': 'Capacitats',
                'ordering': ['tipus', 'capacitat'],
            },
        ),
    ]
