# Generated by Django 4.2.5 on 2024-04-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explotacio', '0006_capacitatestoc_and_more'),
        ('globg', '0003_tipusproducte_delete_categoriacorral'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesproveidor',
            name='tipus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globg.tipusproducte'),
        ),
        migrations.AddField(
            model_name='capacitatestoc',
            name='capacitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.capacitat'),
        ),
        migrations.AddField(
            model_name='capacitatestoc',
            name='tipus_producte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globg.tipusproducte'),
        ),
    ]
