# Generated by Django 4.2.5 on 2024-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globg', '0001_initial'),
        ('explotacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('descripcio', models.TextField(blank=True, null=True, verbose_name='Descripció')),
                ('persona_legal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globg.personalegal')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['persona_legal__nom'],
            },
        ),
        migrations.CreateModel(
            name='Vendes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('data_venta', models.DateField()),
                ('observacions', models.TextField(blank=True, null=True, verbose_name='Observacions')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-data_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetallVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('quantitat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explotacio.articlesproveidor')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.vendes')),
            ],
            options={
                'verbose_name': 'Detall de la venda',
                'verbose_name_plural': 'Detalls de la venda',
                'ordering': ['venda__data_venta'],
            },
        ),
        migrations.CreateModel(
            name='Defuncions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('data_defuncio', models.DateField()),
                ('tipus', models.CharField(choices=[('co', 'Corral'), ('es', 'Escorxador'), ('ce', 'Corral Escorxador'), ('tr', 'Transport'), ('al', 'Altres')], max_length=2)),
                ('justificant', models.FileField(upload_to='defuncions/')),
                ('detall_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.detallvenda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
