# Generated by Django 4.2.5 on 2024-04-24 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_detallvenda_preu_venda_alter_detallvenda_quantitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defuncions',
            name='data_defuncio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='defuncions',
            name='justificant',
            field=models.FileField(blank=True, null=True, upload_to='defuncions/'),
        ),
        migrations.AlterField(
            model_name='defuncions',
            name='tipus',
            field=models.CharField(choices=[('co', 'Corral'), ('es', 'Escorxador'), ('ce', 'Corral Escorxador'), ('tr', 'Transport'), ('al', 'Altres')], default='al', max_length=2),
        ),
    ]
