# Generated by Django 4.2.5 on 2024-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCorral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actiu', models.BooleanField(default=True)),
                ('creat_el_dia', models.DateTimeField(auto_now_add=True)),
                ('modificat_el_dia', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
