# Generated by Django 4.2.5 on 2024-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globg', '0002_documentacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacio',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentacio',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
